version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: daily
      time: "15:00"
      timezone: UTC
    open-pull-requests-limit: 10
    commit-message:
      prefix: build
      include: scope
    ignore:
      - dependency-name: '@salesforce/dev-scripts'
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
