version: 2.1
orbs:
  vault: contentful/vault@1

jobs:
  unit:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm ci
      - run: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - unit
