version: 2.1
orbs:
  vault: contentful/vault@1
  node: circleci/node@5.1.0


jobs:
  lint:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install:
          node-version: '18.15'
      - node/install-packages
      - run: npm run lint
      - run: npm run prettier
      - run: npm run check-types

  unit:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install:
          node-version: '18.15'
      - node/install-packages
      - run: exit 0
      # - run: npm run test-unit # To update in PHX-2687


  integration:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install:
          node-version: '18.15'
      - node/install-packages
      - run: npm run test-integration

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - unit
      - integration:
          context: dev-workflows-test-orgs
