version: 2.1
orbs:
  vault: contentful/vault@1
  node: circleci/node@5.1.0


jobs:
  lint:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install:
          node-version: '18.15'
      - node/install-packages
      - run: npm run lint
      - run: npm run prettier
      - run: npm run check-types

  # unit: # To update in PHX-2687
  #   docker:
  #     - image: cimg/node:lts
  #   steps:
  #     - checkout
  #     - node/install:
  #         node-version: '18.15'
  #     - node/install-packages
  #     - run: npm test-unit

  integration:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install:
          node-version: '18.15'
      - node/install-packages
      - run: npm test-integration

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - unit
